version: '3.8'

services:
 okta-feed-me-well-db:
   container_name: okta-feed-me-well-db
   image: mysql
   command: --default-authentication-plugin=mysql_native_password
   restart: always
   ports:
     - 3389:3306
   environment:
     MYSQL_ROOT_PASSWORD: ''
     MYSQL_DATABASE: 'employee'
     MYSQL_USER: 'root'
     MYSQL_PASSWORD: ''